### ISSUE TITLE
Does not use native trash functionality (unlike Atom)

### ISSUE THREAD

**Issue by atombender** [filipesabella/quick-file-actions#4]
I just lost an hour's work because I used the quick delete to delete the wrong file. I trusted this package to use the native trash functionality (the trashcan on OS X), which Atom does. However, looking at the code, your package actually permanently deletes the file, and there's no undo operation.

This, in my mind, makes its delete functionality completely unusable.

If this is intended behavior, I hope you will at least put a large bold warning in the readme to warn off other users.

**Comment by DJTB** [comment]
I love all the other quick file actions - really really useful.

Agreed on this point though. I recommend for anyone else coming across this to add the following to your keymap.cson to trash the current file:
```
# avoid permanent deletion used by Quick File Actions package = prefer Atom's Tree View: Remove
'atom-workspace':
  'ctrl-alt-f d': 'tree-view:remove'
```
You lose some of the path resolving abilities of quick-file-actions for deletion, but for me at least I'm generally only using keyboard shortcuts in atom to delete the current open file. Bonus functionality: if the file has no changes/was saved - Atom will close the tab for you after trashing it :balloon:

**Comment by filipesabella** [comment]
Hilariously enough github didn't notify me of new issues in this repo.

Sorry for the massive delay, but the feature has been implemented. It's now the default behaviour to send files to the trash bin, but I've also added an option for that.
